server:
  shutdown: graceful

spring:
  profiles:
    active: prod
  lifecycle:
    timeout-per-shutdown-phase: 20s

#management:
#  endpoint:
#    health:
#      probes:
#        enabled: true

---

spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    org.devocative: debug
